development:
  clients:
    default:
      database: demo_center_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: demo_center_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
